### ISSUE TITLE
FP Chatbot on Telegram- View My Profile flow

### ISSUE THREAD

**Issue by anjanarao24** [FightPandemics/FightPandemics-Telegram#10]
User story Goal : As a FightPandemic chatbot user, I should be able to View my profile so that I can see my Profile information to be able to edit it if necessary

1. Use case 1 : View Profile for a Logged in User
User invokes Main menu at any point with the command /Mainmenu
#3 FP Chatbot on Telegram- Main Menu flow [https://github.com/FightPandemics/FightPandemics-Telegram/issues/3](url)
User gets the Options to Select on the Screen : 
                                            

-                                             Offer Help
-                                             Request Help
-                                             View my Profile
-                                             View my Posts
-                                             Signout
-                                             About Us

User Taps to select "View my Profile"
**Wireframe:** 
https://miro.com/app/board/o9J_kp0wo_Y=/?moveToWidget=3074457349708917387&cot=12

User is taken to the Individual Profile screen of the User
**Wireframe:**
https://miro.com/app/board/o9J_kp0wo_Y=/?moveToWidget=3074457349042367936&cot=3

User can see the buttons "Edit Profile" and "View Account Settings" at the bottom of the screen
**Wireframe:**
https://miro.com/app/board/o9J_kp0wo_Y=/?moveToWidget=3074457349042367936&cot=3

On the View Profile screen User should be able to see the following fields:

- Name
- Self Introduction
- Facebook URL
- LinkedIn URL
-GitHub URL
-Twitter URL
- Personal Website URL

2. Use case 2 : View Profile for a Non Logged in User

A Non logged in User will not have the Option to "View My Profile" and will have to Login inorder to "View My Profile"

If he clicks "View my Profile" he gets a message " Please login inorder to be able to view Your Profile"

User invokes Main menu at any point with the command /Mainmenu

**Wireframe :** https://miro.com/app/board/o9J_kp0wo_Y=/?moveToWidget=3074457349708917388&cot=12
User gets the Options to Select on the Screen : 
                                            

-                                             Offer Help
-                                              Request Help
-                                              View my Posts
-                                              View my Profile
-                                             Create Posts
-                                             Login
-                                             About Us

Once User selects Login/Signup #5 FP Chatbot on Telegram- Login integration and Signup flow [https://github.com/FightPandemics/FightPandemics-Telegram/issues/5](url)

**WireFrame** : 
https://miro.com/app/board/o9J_kp0wo_Y=/?moveToWidget=3074457349121133923&cot=12

On Logging in OR Signing up he can Invoke the Main Menu and go to Use case 1 flow in order to "View my Profile"

**Acceptance Criteria:**

1. User should be able to View Profile Option using the Main Menu command
2. User should be able to see to Option to View Profile if Not logged in to the Chatbot application but would need to login inorder to View profile 
3. On Viewing the Profile User should have the Option to Edit the Profile and also View the Account settings
4. User should not be able to edit the Profile fields on the View profile screen

**Comment by omerkhan3** [comment]
### API Integration
**​View My Profile** - GET  _/api​/users​/current_
**Updae My Profile** - PATCH _/api/users/current_

**Comment by emtay** [comment]
**Completed incorporating** - @anjanarao24 Looks good except needs to be updated to the new screens. Also, remove the button screenshots so it's not confusing which is the right layout? Thanks!

**Comment by kumudchauhan** [comment]
Implemented for signed users, hence closing this issue.
