### ISSUE TITLE
FP Chatbot flow on Telegram from Welcome/Start to Request Other Help flow for Logged in User from Main menu

### ISSUE THREAD

**Issue by anjanarao24** [FightPandemics/FightPandemics-Telegram#15]
**Use case 1A :** Request Other help -->Grocery /Food for a Logged in User from Main menu

A. User invokes Main menu at any point with the command /Mainmenu
#3 FP Chatbot on Telegram- Main Menu flow [https://github.com/FightPandemics/FightPandemics-Telegram/issues/3](url)
User gets the Options to Select on the Screen : 
                                            

-                                             Restart offer Help
-                                             Restart Request Help
-                                             View my Profile
-                                             View my Posts
-                                             Signout
-                                             About FightPandemic

B. User Taps to select "Restart Request Help"

C. User is asked "What kind of help do you want?"

1. Medical Help
2. Other Help
3. Go to main menu

D. User selects by Tapping on the screen " Other Help"

E. User is presented with a screen to select the different types of Help he would like to offer (From a menu of 9 options)

F. User selects 'Grocery/Food" option from the Menu

G. User is asked to select the location to provide the Results closest to his/her location "Please let us know your location so we can share the resources closest to you! You can send your location or begin typing a different location!"

H.User Sends the location where he is located

I. User is provided with a Intermittent message that he will be redirected to the results shorlty "Thank you for sending your location! We are accessing your location and will return your results in a moment!"
H. User is taken to the View Posts screen #4 FP Chatbot on Telegram - View Posts flow to view the posts related to Grocery/Food
https://github.com/FightPandemics/FightPandemics-Telegram/issues/4

Wireframe for the flow : [HERE](https://miro.com/app/board/o9J_kp0wo_Y=/?moveToWidget=3074457349121106552&cot=1)

**Comment by anjanarao24** [comment]
**Use case 1B :** Request Other help -->Medical Supplies for a Logged in User from Main menu


A. User invokes Main menu at any point with the command /Mainmenu
#3 FP Chatbot on Telegram- Main Menu flow [https://github.com/FightPandemics/FightPandemics-Telegram/issues/3](url)
User gets the Options to Select on the Screen : 
                                            

-                                             Restart offer Help
-                                             Restart Request Help
-                                             View my Profile
-                                             View my Posts
-                                             Signout
-                                             About FightPandemic

B. User Taps to select "Restart Request Help"


C. User is asked "What kind of help do you want?"

1. Medical Help
2. Other Help
3. Go to main menu



D. User selects by Tapping on the screen " Other Help"

E. User is presented with a screen to select the different types of Help he would like to offer (From a menu of 9 options)

F. User selects 'Medical Supplies" option from the Menu

G. User is asked to select the location to provide the Results closest to his/her location "Please let us know your location so we can share the resources closest to you! You can send your location or begin typing a different location!"

H.User Sends the location where he is located

I. User is provided with a Intermittent message that he will be redirected to the results shorlty "Thank you for sending your location! We are accessing your location and will return your results in a moment!"
H. User is taken to the View Posts screen #4 FP Chatbot on Telegram - View Posts flow to view the posts related to Grocery/Food
https://github.com/FightPandemics/FightPandemics-Telegram/issues/4

Wireframe for the flow : [HERE](https://miro.com/app/board/o9J_kp0wo_Y=/?moveToWidget=3074457349121106552&cot=1)

**Comment by anjanarao24** [comment]
**Use case 1C :** Request Other help -->Funding/Donate for a Logged in User from Main menu
Use case 1D : Request Other help -->Well-Being/Mental for a Logged in User from Main menu
Use case 1E : Request Other help -->Information for a Logged in User from Main menu
Use case 1F : Request Other help -->Technology for a Logged in User from Main menu
Use case 1G : Request Other help -->Legal for a Logged in User from Main menu
Use case 1H : Request Other help -->Education for a Logged in User from Main menu
Use case 1I : Request Other help -->Business or a Logged in User from Main menu

**Comment by kumudchauhan** [comment]
The user story is not updated but the Request help flow has been implemented and functional.
