### ISSUE TITLE
FP Chatbot flow on Telegram from Welcome/Start to Request Other Help flow for Non Logged in User from Main menu 

### ISSUE THREAD

**Issue by anjanarao24** [FightPandemics/FightPandemics-Telegram#16]
*Use case 1A :** Request Other help-->Grocery /Food for a non Logged in User (Non Logged in User flow is same as Logged in User flow until the point of Viewing posts, but he cannot Create posts or Comment and will be prompted to login for Creating posts/Comment)

A. User invokes Main menu at any point with the command /Mainmenu
#3 FP Chatbot on Telegram- Main Menu flow [https://github.com/FightPandemics/FightPandemics-Telegram/issues/3](url)
User gets the Options to Select on the Screen : 
                                            

-                                             Restart offer Help
-                                             Restart Request Help
-                                             View my Profile
-                                             View my Posts
-                                            Login/Signup
-                                             About FightPandemic

B. User Taps to select "Restart Request Help"

C. User is asked "What kind of help do you want?"

1. Medical Help
2. Other Help
3. Go to main menu

D. User selects by Tapping on the screen " Other Help"

E. User is presented with a screen to select the different types of Help he would like to offer (From a menu of 9 options)

F. User selects 'Grocery/Food" option from the Menu

G. User is asked to select the location to provide the Results closest to his/her location "Please let us know your location so we can share the resources closest to you! You can send your location or begin typing a different location!"

H.User Sends the location where he is located

I. User is provided with a Intermittent message that he will be redirected to the results shorlty "Thank you for sending your location! We are accessing your location and will return your results in a moment!"
H. User is taken to the View Posts screen #4 FP Chatbot on Telegram - View Posts flow to view the posts related to Grocery/Food
https://github.com/FightPandemics/FightPandemics-Telegram/issues/4

Wireframe for the flow : [HERE](https://miro.com/app/board/o9J_kp0wo_Y=/?moveToWidget=3074457349121133892&cot=12)

J. User tries to Create New post to request help or Comment on an existing post for help:
User is then prompted to login in for going ahead 

Wireframe for the flow : [HERE](https://miro.com/app/board/o9J_kp0wo_Y=/?moveToWidget=3074457349121133922&cot=12)

**Comment by anjanarao24** [comment]
*Use case 1B :** Request Other help-->Medical supplies for a non Logged in User (Non Logged in User flow is same as Logged in User flow until the point of Viewing posts, but he cannot Create posts or Comment and will be prompted to login for Creating posts/Comment)

A. User invokes Main menu at any point with the command /Mainmenu
#3 FP Chatbot on Telegram- Main Menu flow [https://github.com/FightPandemics/FightPandemics-Telegram/issues/3](url)
User gets the Options to Select on the Screen : 
                                            

-                                             Restart offer Help
-                                             Restart Request Help
-                                             View my Profile
-                                             View my Posts
-                                            Login/Signup
-                                             About FightPandemic

B. User Taps to select "Restart Request Help"


C. User is asked "What kind of help do you want?"

1. Medical Help
2. Other Help
3. Go to main menu


D. User selects by Tapping on the screen " Other Help"

E. User is presented with a screen to select the different types of Help he would like to offer (From a menu of 9 options)

F. User selects 'Medical supplies" option from the Menu

G. User is asked to select the location to provide the Results closest to his/her location "Please let us know your location so we can share the resources closest to you! You can send your location or begin typing a different location!"

H.User Sends the location where he is located

I. User is provided with a Intermittent message that he will be redirected to the results shorlty "Thank you for sending your location! We are accessing your location and will return your results in a moment!"
H. User is taken to the View Posts screen #4 FP Chatbot on Telegram - View Posts flow to view the posts related to Grocery/Food
https://github.com/FightPandemics/FightPandemics-Telegram/issues/4

Wireframe for the flow : [HERE](https://miro.com/app/board/o9J_kp0wo_Y=/?moveToWidget=3074457349121133892&cot=12)

J. User tries to Create New post to request help or Comment on an existing post for help:
User is then prompted to login in for going ahead 

Wireframe for the flow : [HERE](https://miro.com/app/board/o9J_kp0wo_Y=/?moveToWidget=3074457349121133922&cot=12)

**Comment by anjanarao24** [comment]
**Use case 1C:**Request Other help for non Logged in User from Main Menu --> Funding /Donate(Non Logged in User flow is same as Logged in User flow until the point of Viewing posts, but he cannot Create posts or Comment and will be prompted to login for Creating posts/Comment)

Use case 1D:Request Other help for non Logged in User from Main Menu --> Well-Being /Mental(Non Logged in User flow is same as Logged in User flow until the point of Viewing posts, but he cannot Create posts or Comment and will be prompted to login for Creating posts/Comment)

Use case 1E:Request Other help for non Logged in User from Main Menu  --> Information(Non Logged in User flow is same as Logged in User flow until the point of Viewing posts, but he cannot Create posts or Comment and will be prompted to login for Creating posts/Comment)

Use case 1F:Request Other help for non Logged in User from Main Menu  --> Technology (Non Logged in User flow is same as Logged in User flow until the point of Viewing posts, but he cannot Create posts or Comment and will be prompted to login for Creating posts/Comment)

Use case 1G:Request Other help for non Logged in User from Main Menu --> Legal (Non Logged in User flow is same as Logged in User flow until the point of Viewing posts, but he cannot Create posts or Comment and will be prompted to login for Creating posts/Comment)

Use case 1H:Request Other help for non Logged in User from Main Menu  --> Education(Non Logged in User flow is same as Logged in User flow until the point of Viewing posts, but he cannot Create posts or Comment and will be prompted to login for Creating posts/Comment)

Use case 1I: Request Other help for non Logged in User from Main Menu  --> Business(Non Logged in User flow is same as Logged in User flow until the point of Viewing posts, but he cannot Create posts or Comment and will be prompted to login for Creating posts/Comment)

**Comment by kumudchauhan** [comment]
Request help flow for different categories has been implemented.
