### ISSUE TITLE
FP Chatbot flow on Telegram from Welcome/Start to Offer Help flow for non Logged in User

### ISSUE THREAD

**Issue by anjanarao24** [FightPandemics/FightPandemics-Telegram#17]
Offer help -->Grocery /Food or any other type for a Non Logged in User from Main menu

A. User invokes Main menu at any point with the command /Mainmenu
#3 FP Chatbot on Telegram- Main Menu flow [https://github.com/FightPandemics/FightPandemics-Telegram/issues/3](url)
User gets the Options to Select on the Screen : 
                                            

-                                             Offer Help
-                                             Request Help
-                                             View my Profile
-                                             View my Posts
-                                             Create Post
-                                              Login
-                                             About Us

B. User Taps to select "Offer Help"

C. User is presented with a screen to select the different types of Help he would like to offer (From a menu of 9 options)

F. User can select multiple options from that Menu and then click on Done.

G. User is asked to select the location to provide the Results closest to his/her location "Please let us know your location so we can share the resources closest to you! You can send your location or begin typing a different location!"

H.User Sends the location where he is located

I. User is provided with a Intermittent message that he will be redirected to the results shorlty "Thank you for sending your location! We are accessing your location and will return your results in a moment!"
H. User is taken to the View Posts screen #4 FP Chatbot on Telegram - View Posts flow to view the posts related to Grocery/Food or any other type
https://github.com/FightPandemics/FightPandemics-Telegram/issues/4

Wireframe for the flow : [HERE](https://miro.com/app/board/o9J_kp0wo_Y=/?moveToWidget=3074457349708917388&cot=12)

**Comment by kumudchauhan** [comment]
Implemented
