### ISSUE TITLE
Get Code Base Set up

### ISSUE THREAD

**Issue by emtay** [FightPandemics/FightPandemics-Telegram#19]
As a dev team, we need start the environment for our telegram bot so that other engineers can contribute.

**Comment by larryabim** [comment]
# Code Base Set up

As discussed today we need to set up an environment for us to start working on.

# Github 
 I think from some of my minimal previous experience the team needs a structured workflow first of all with working with Github. This includes how to set up branches, pull requests, and requirements for merging code into master. Also, marking down for new users how exactly they should run this code locally on their machine. In addition, should also markdown on the readme file coding standards developers should follow so the codebase is the same.

# Codebase
For the codebase, we need a template to work with. I don't know if other GitHub repositories have something similar to Telegram and python. But however, we discussed in the meeting that we want to work with the API calls. I think Josh said he can help us with that but we need to make sure that we have the backend portion set up also before we start coding. :)  

In addition, we need to look at also test cases and how we set up testing with the codebase. 

# Extras

For Github as a team, we should also look at using Travis CI. This is used to help run our tests and make sure our code compiles before merging branches into master.

**Comment by kumudchauhan** [comment]
For the environment setup, Please follow the instructions of the README file of the following link.
https://github.com/FightPandemics/FightPandemics-Telegram

**Comment by kumudchauhan** [comment]
Merged my dev branch to the main repo's dev https://github.com/FightPandemics/FightPandemics-Telegram/tree/dev

**Comment by kumudchauhan** [comment]
The codebase is setup and major refactoring has been done by Axel's PR. Hence closing this ticket.
