### ISSUE TITLE
FP Chatbot flow on Telegram from Welcome/Start to Offer Help flow for Logged in User from Main menu

### ISSUE THREAD

**Issue by anjanarao24** [FightPandemics/FightPandemics-Telegram#2]
**Use case 1A :** Offer help -->Grocery /Food for a Logged in User from Main menu

A. User invokes Main menu at any point with the command /Mainmenu
#3 FP Chatbot on Telegram- Main Menu flow [https://github.com/FightPandemics/FightPandemics-Telegram/issues/3](url)
User gets the Options to Select on the Screen : 
                                            

-                                             Offer Help
-                                             Request Help
-                                             View my Profile
-                                             View my Posts
-                                             Create Post
-                                             Signout
-                                             About Us

B. User Taps to select "Offer Help"

C. User is presented with a screen to select the different types of Help he would like to offer (From a menu of 9 options)

F. User can select multiple options from that Menu and then click on Done.

G. User is asked to select the location to provide the Results closest to his/her location "Please let us know your location so we can share the resources closest to you! You can send your location or begin typing a different location!"

H.User Sends the location where he is located

I. User is provided with a Intermittent message that he will be redirected to the results shorlty "Thank you for sending your location! We are accessing your location and will return your results in a moment!"
H. User is taken to the View Posts screen #4 FP Chatbot on Telegram - View Posts flow to view the posts related to Grocery/Food
https://github.com/FightPandemics/FightPandemics-Telegram/issues/4

Wireframe for the flow : [HERE](https://miro.com/app/board/o9J_kp0wo_Y=/?moveToWidget=3074457349121133913&cot=12)

**Comment by anjanarao24** [comment]
**Use case 1B :** Offer help -->Medical Supplies for a Logged in User from Main menu


A. User invokes Main menu at any point with the command /Mainmenu
#3 FP Chatbot on Telegram- Main Menu flow [https://github.com/FightPandemics/FightPandemics-Telegram/issues/3](url)
User gets the Options to Select on the Screen : 
                                            

-                                             Restart offer Help
-                                             Restart Request Help
-                                             View my Profile
-                                             View my Posts
-                                             Signout
-                                             About FightPandemic

B. User Taps to select "Restart Offer Help"


C. User is presented with a screen to select the different types of Help he would like to offer (From a menu of 9 options)

F. User selects 'Medical Supplies" option from the Menu

G. User is asked to select the location to provide the Results closest to his/her location "Please let us know your location so we can share the resources closest to you! You can send your location or begin typing a different location!"

H.User Sends the location where he is located

I. User is provided with a Intermittent message that he will be redirected to the results shortly "Thank you for sending your location! We are accessing your location and will return your results in a moment!"
H. User is taken to the View Posts screen #4 FP Chatbot on Telegram - View Posts flow to view the posts related to Grocery/Food
https://github.com/FightPandemics/FightPandemics-Telegram/issues/4

Wireframe for the flow : [HERE](https://miro.com/app/board/o9J_kp0wo_Y=/?moveToWidget=3074457349121133901&cot=12)

**Comment by anjanarao24** [comment]
Use case 1C : Offer help -->Funding/Donate for a Logged in User from Main menu
Use case 1D : Offer help -->Well-Being/Mental for a Logged in User from Main menu
Use case 1E : Offer help -->Information for a Logged in User from Main menu
Use case 1F : Offer help -->Technology for a Logged in User from Main menu
Use case 1G : Offer help -->Legal for a Logged in User from Main menu
Use case 1H : Offer help -->Education for a Logged in User from Main menu
Use case 1I : Offer help -->Business or a Logged in User from Main menu

**Comment by kumudchauhan** [comment]
Implemented, hence closing this.
