### ISSUE TITLE
FP Chatbot on Telegram-Main menu flow

### ISSUE THREAD

**Issue by anjanarao24** [FightPandemics/FightPandemics-Telegram#3]
User story: As a FP chatbot user, I want to be able to invoke the Main menu at any point inorder to see the different options for help, signout, login , About FP etc.

Use case : User invokes the Main menu using the Main menu command /Mainmenu  when he is logged in or not logged in to the chatbot app

User types the command /MainMenu at any point in the chatbot

User views different Main menu options based on his Signed in or Not Signedin Status:

**Signed in:**

**Miro** : https://miro.com/app/board/o9J_kp0wo_Y=/?moveToWidget=3074457349708917387&cot=12

**Not Signed in:**
**Miro**: https://miro.com/app/board/o9J_kp0wo_Y=/?moveToWidget=3074457349708917388&cot=12

He selects the various options and is redirected to #2, #15, #16, #17,OR  #5

Incorporating comment below: Regarding About Fight Pandemics page: Will redirect to the Webapp.

(** If we want to encourage any actions from the user at that point (like, volunteer, follow/like us on social media) - Future version feature additions)

**Comment by kumudchauhan** [comment]
I am working on the main menu implementation.

**Comment by CamilaArias** [comment]
**Completed incorporating** : We haven't defined what "About" shows. We need a text for that, and figure out if we want to encourage any actions from the user at that point (like, volunteer, follow/like us on social media)

**Comment by kumudchauhan** [comment]
This functionality has been implemented, closing the ticket.
