### ISSUE TITLE
FP Chatbot on Telegram- Signout flow

### ISSUE THREAD

**Issue by anjanarao24** [FightPandemics/FightPandemics-Telegram#9]
**User story**: As a chatbot user, I want to be able to signout of my FP account at any time so that I can feel secure that no one else can access my account and I want to be able to confirm I'm signing out so I don't sign out by accident.

**Use case 1**: User invokes /Sign out command from Telegram menu or clicks on the "Sign Out" button. When they get the message "Are you sure you want to sign out?", user confirms "Yes".

Then user gets confirmation: "You have successfully signed out of FightPandemics!"  with the Main Menu buttons: 
[ offer help] [ request help] 
etc. 
Here is issue to pull in Main Menu:
https://github.com/FightPandemics/FightPandemics-Telegram/issues/3

**Wireframe:**
https://miro.com/app/board/o9J_kp0wo_Y=/?moveToWidget=3074457349347689489&cot=12

**Use case 2**: User invokes /Sign out command and chooses to stay logged in.

After entering message "/Sign out" in the command line,
User gets get the message "Are you sure you want to sign out?" with options [Yes] or [No, keep me logged in]
User selects "No, keep me logged in"
User gets confirmation "You are still logged in to FightPandemics! What would you like to do next?" with the Main Menu buttons: 
[offer help] [request help] 
etc. 
Here is issue to pull in Main Menu:
https://github.com/FightPandemics/FightPandemics-Telegram/issues/3

**Wireframe:**
https://miro.com/app/board/o9J_kp0wo_Y=/?moveToWidget=3074457349347732961&cot=12

**Acceptance Criteria:**
A. Given User enters "/Sign out" from command line,
When they see the request for confirmation _"Are you sure you want to sign out?"_ and choose _"Yes"_,
Then they will be signed out from FP and they will get the command: 
_"You have successfully signed out of FightPandemics! 
What would you like to do next?"_  with the Main Menu buttons displayed.

B. Given User enters "/Sign out" from command line,
When they see the request for confirmation "_Are you sure you want to sign out?"_ and choose _"No, keep me logged in"_,
Then they will not be signed out from FP and they will get the command: 
_"You are still logged in to FightPandemics!
What would you like to do next?"_ with the Main Menu buttons displayed.

C. Given User successfully signs out
When user re-engages with FP bot
Then user will be prompted to login whenever they try to create post, comment, view author profile, view my profile as if they were a new user.

**Comment by emtay** [comment]
A. User invokes Main menu at any point with the command /Mainmenu or can go directly to /Signout
#3 FP Chatbot on Telegram- Main Menu flow https://github.com/FightPandemics/FightPandemics-Telegram/issues/3

User gets the Options to Select on the Screen :
/Restart offer Help
/Restart Request Help
/Login/Signup
/View My Profile
/View My Posts
/Signout
/About FightPandemics

User selects /Signout

User then gets response confirmation: "You have successfully signed out."

Wireframe:
https://miro.com/app/board/o9J_kp0wo_Y=/?moveToWidget=3074457348991333377&cot=6

B. User invokes Sign out at any point with the command /Signout

User gets response confirmation: "You have successfully signed out."

AC:
A. Given User enters /Main Menu
When user selects "Signout"
Then they will be signed out from FP and they will get the command "You have successfully signed out."

B. Given User enters /Signout
When user clicks enter
Then they will be signed out from FP and they will get the command "You have successfully signed out."

C. Given User successfully signs out
When user re-engages with FP bot
Then user will be prompted to login whenever they try to create post, comment, view author profile, view my profile as if they were a new user.

**Comment by kumudchauhan** [comment]
Signout flow is implemented using Signout button-through main menu.
